### ISSUE TITLE
Communicate with slack user when pushed to a not listened branch

### ISSUE THREAD

**Issue by ChopperLee2011** [ChopperLee2011/github-branch-deploy-bot#2]
- [x] talk to whom ? github account can't link to a slack account.
- [x] send message to slack.
- [x] slack question design.
- [x] send request to start deployment, when user asked.

**Comment by ilyamochalov** [comment]
@ChopperLee2011 I am looking at your `index.js, have few questions:
- I am not sure why you add a new route here https://github.com/ChopperLee2011/github-branch-deploy-bot/blob/master/index.js#L40  , please explain the idea;
- How / where you handling user response from a slack channel (response is information on which button was pressed)? I saw this method `postToChannel` (https://github.com/ChopperLee2011/github-branch-deploy-bot/blob/master/lib/slack/SlackBot.js#L30) but couldn't find the event handler.

**Comment by ChopperLee2011** [comment]
1. the idea for adding a route is handling the HTTP request sent by the user clicks the button.
2. a [button](https://api.slack.com/reference/block-kit/block-elements#button) in Slack block element can fire a request, and yes I am not fulfilling the parameter yet.

**Comment by ilyamochalov** [comment]
@ChopperLee2011 noted. I was looking at nodejs package you are using and it seems we can add response handler: https://www.npmjs.com/package/slackbots#response-handler , can we integrate this with interactive message you are using?

**Comment by ChopperLee2011** [comment]
feature implemented, closing
